# Generated by Django 4.0.7 on 2022-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationDetails',
            fields=[
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256)),
                ('verification_code', models.PositiveBigIntegerField()),
                ('verification_status', models.BooleanField(default=False)),
                ('email_entry_attempts', models.PositiveBigIntegerField(default=0)),
                ('code_verification_attempts', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
