# Generated by Django 4.0.7 on 2022-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdetails',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userverificationdetails',
            name='verification_code',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
