# Generated by Django 4.0.7 on 2022-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_userverificationdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdetails',
            name='email',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
