# Generated by Django 4.0.7 on 2022-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_alter_userverificationdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdetails',
            name='verification_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
