# Generated by Django 4.0.7 on 2022-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_alter_userverificationdetails_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdetails',
            name='email',
            field=models.CharField(blank=True, default='empty', max_length=256),
        ),
    ]
