# Generated by Django 4.0.7 on 2022-10-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_alter_userverificationdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdetails',
            name='email',
            field=models.CharField(blank=True, default='empty', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userverificationdetails',
            name='verification_code',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
