# Generated by Django 4.0.8 on 2023-01-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_alter_userverificationdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationdetails',
            name='user_type',
            field=models.CharField(choices=[('WRITER', 'Writer'), ('CLIENT', 'Client'), ('UNVERIFIED', 'Unverified'), ('FIRST_TIME_USER', 'First_time_user')], default='FIRST_TIME_USER', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
